import pygame

class WINDOW:
	MIN_WIDTH = 500
	MIN_HEIGHT = 500
	
	WIDTH = 500
	HEIGHT = 500
	SIZE = WIDTH, HEIGHT

	CLOCK = pygame.Clock()

class SPRITE:
	WIDTH = 16
	HEIGHT = 16
	SIZE = WIDTH, HEIGHT

class CELLS:
	WIDTH = SPRITE.WIDTH
	HEIGHT = SPRITE.HEIGHT
	SIZE = WIDTH, HEIGHT

class UPDATE:
	INPUT_CHECKS_PER_SEC = 15
	FPS = 60

class GAME:
	PLAYER_SPEED = 8
	FIELD_OF_VIEW_IN_PERCENT = 0.8 
	ALLOWABLE_NUMBER_OF_ENEMIES = 10
	MAX_DISTANCE_FROM_PLAYER = 25

class COLOURS:
	BLACK = (0, 0, 0)
	RED = (255, 0, 0)
	BLUE = (0, 0, 255)

class DEBUG:
	ENABLED = False
	PLAYER_COLOR = COLOURS.BLUE
	ENEMY_COLOR = COLOURS.RED

class CAMERA:
	ZOOM =  WINDOW.HEIGHT / ( CELLS.HEIGHT * GAME.MAX_DISTANCE_FROM_PLAYER * GAME.FIELD_OF_VIEW_IN_PERCENT)
	WIDTH = WINDOW.WIDTH / ZOOM
	HEIGHT = WINDOW.HEIGHT / ZOOM

	SIZE = WIDTH, HEIGHT
	@classmethod
	def update(cls):
		pass


class CONTROLS:
	UP = (pygame.K_w, pygame.K_UP)
	DOWN = (pygame.K_s, pygame.K_DOWN)
	LEFT = (pygame.K_a, pygame.K_LEFT)
	RIGHT = (pygame.K_d, pygame.K_RIGHT)

window = pygame.display.set_mode(WINDOW.SIZE, pygame.RESIZABLE)