class WINDOW:
	WIDTH = 500
	HEIGHT = 500
	SIZE = WIDTH, HEIGHT

class MAP:
	ROWS = 20
	COLS = 20
	SIZE = ROWS, COLS

class CELLS:
	WIDTH = WINDOW.WIDTH // MAP.COLS
	HEIGHT = WINDOW.HEIGHT // MAP.ROWS
	SIZE = WIDTH, HEIGHT