from Globals import Settings


world = {}
spatial_grid = {}

camera = {}

PLAYER_ID = 1
NEXT_ENTITY_ID = 1
NEXT_DEBUG_ELEMENT_ID = 1

GAME_RUNNING = True
CURRENT_STATE = "MENU"
IS_LEVELING_UP = False
IS_PAUSED = False
CURRENT_FPS = 60

# DIFFICULTY SCALING
GAME_TIME = 0.0
BOSS_TIMER = Settings.GAME.BOSS_SPAWN_TIME_DELAY
KILLS_COUNT = 0

SCREEN_MOUSE_POS = (-1, -1)
UI_DIRTY = True
CACHED_UI_SURFACE = None


def reset():
    global GAME_TIME, BOSS_TIMER, KILLS_COUNT, IS_PAUSED, IS_LEVELING_UP

    GAME_TIME = 0.0
    BOSS_TIMER = Settings.GAME.BOSS_SPAWN_TIME_DELAY
    KILLS_COUNT = 0
    IS_LEVELING_UP = False
    IS_PAUSED = False
